---
title: "signdata-combined"
format: pdf
message: FALSE
warning: FALSE
---

```{r}
# load libraries and data
library(readxl)
library(writexl)
library(tidyverse)

asllrp <- read_excel("~/Desktop/Downloads/REUAICT/Real-Code/Data-Cleaning/ASL-Data/asllrp_sentence_signs.xlsx")

dsp <- read_excel("~/Desktop/Downloads/REUAICT/Real-Code/Data-Cleaning/ASL-Data/dsp_sentence_signs.xlsx")

utterances <- read_excel("~/Desktop/Downloads/REUAICT/Real-Code/Data-Cleaning/ASL-Data/consolidated_sign_data.xlsx")
```

```{r}
#standardize columns and prepare for join
asllrp <- asllrp |>
  mutate(
    UID = (str_extract(UID, "\\d+")),
  )

dsp <- dsp |>
  mutate(
    UID = (str_extract(UID, "\\d+")), 
  )

utterances <- utterances |>
  mutate(
    UID =(str_extract(UID, "\\d+")))
```

```{r}
# join data based on utterance id (UID)

asllrp_joined <- full_join(utterances, asllrp, by = c("UID")) |>
  filter(!is.na(Gloss),!is.na(Translation), !is.na(UID), !is.na(VID) )

dsp_joined <- full_join(utterances, dsp, by = c("UID"))
```